name: "Sync ProjectV2 Field"
description: "A GitHub Action to sync ProjectV2 field one organization-level boards with a value from and item's properties"
inputs:
  project_id:
    required: true
    description: "ID of the project to update"
  item_property:
    required: true
    description: "Name of the item property to use as the value for the ProjectV2 field"
  org:
    required: true
    description: "Name of the organization"
  sync_field:
    required: true
    description: "Name of the ProjectV2 field to update"
  github_token:
    required: true
    description: "GitHub token with project write access"
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pass in inputs
      run: |
        echo "PROJECT_ID=${{ inputs.project_id }}" >> $GITHUB_ENV
        echo "ITEM_PROPERTY=${{ inputs.item_property }}" >> $GITHUB_ENV
        echo "ORG=${{ inputs.org }}" >> $GITHUB_ENV
        echo "SYNC_FIELD=${{ inputs.sync_field }}" >> $GITHUB_ENV
        echo "GITHUB_API_TOKEN=${{ inputs.github_token }}" >> $GITHUB_ENV
      shell: bash
    - name: Run the sync
      id: run-sync
      run: |
        python src/sync.py
      shell: bash